# Generated by Django 3.2 on 2021-04-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210421_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msgid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phonenumber', models.CharField(default='', max_length=70)),
                ('message', models.CharField(default='', max_length=600)),
            ],
        ),
    ]
